feat: add statics service
catarena-s/java-explore-with-me pull request #3
Opened 2023-06-15 20:12 UTC by catarena-s

2023-06-16 19:37 UTC, z8q requested changes

2023-06-16 19:37 UTC, z8q commented on ewm-stats-server/stats-server/src/main/java/ru/practicum/controller/StatsServerController.java
> +        }
Много логики для контроллера

2023-06-17 13:59 UTC, catarena-s commented on ewm-stats-server/stats-server/src/main/java/ru/practicum/controller/StatsServerController.java
> +        }
Проверку времени перенесла в сервис

2023-06-17 13:59 UTC, catarena-s commented on ewm-stats-server/stats-server/pom.xml
> +            <version>${spring.boot.version}</version>
лишние версии зависимостей убрала

2023-06-17 14:00 UTC, catarena-s commented on pom.xml
> +    <dependencies>
перенесла зависимости в модули

2023-06-18 11:15 UTC, z8q approved these changes

2023-06-18 11:51 UTC, merged