Main svc
catarena-s/java-explore-with-me pull request #4
Opened 2023-06-26 19:06 UTC by catarena-s

2023-06-27 20:59 UTC, z8q requested changes

2023-06-27 20:59 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/api/pub/PublicCompilationController.java
> +                                                @PositiveOrZero @RequestParam(value = "from", defaultValue = FROM) Integer from,
Для работы `@PositiveOrZero` забыли `@Validated`

2023-06-27 20:59 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/api/privet/PrivetEventController.java
> +public class PrivetEventController {
Опечатка)

2023-06-27 20:59 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/dto/request/EventRequestStatusUpdateRequest.java
> +    private String status;
на статусах лучше использовать enum

2023-06-27 20:59 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/enums/RequestStatus.java
> +    public static RequestStatus from(String name) {
Такие конструкции можно использовать, когда у каждого элемента есть какие-то значения.
В общем тут в трех ответах все есть:
https://stackoverflow.com/questions/604424/how-to-get-an-enum-value-from-a-string-value-in-java
В третьем предлагают сделать мапу, которая создается при запуске приложения, чтобы быстрее потом доставать нужное значение, не запуская for на каждом обращении.

Но конкретно тут RequestStatus.valueOf("PENDING") сработало бы правильно.
А если бы указали недопустимое значение, то также будет IllegalArgumentException

В других enum-ах тоже можно посмотреть

2023-06-27 20:59 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/service/category/CategoryServiceImpl.java
> +    @Transactional
Не уверен, есть ли здесь смысл использовать `@Transactional`
Внутри метода обращение к базе выполняет только один save, а если в него провалиться, то увидишь, что сам он уже помечен этой аннотацией

2023-06-27 20:59 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/service/event/EventServiceImpl.java
> +                .get();
чтобы get не подсвечивался, можно использовать какие-то такие конструкции:
```
final LocalDateTime start = events.stream()
                .map(Event::getPublishedOn)
                .min(LocalDateTime::compareTo)
                .orElse(null);
```

2023-06-28 13:55 UTC, catarena-s commented on ewm-service/src/main/java/ru/practicum/enums/RequestStatus.java
> +    public static RequestStatus from(String name) {
сделала общий мареп для эвентов

2023-06-28 13:55 UTC, catarena-s commented on ewm-service/src/main/java/ru/practicum/dto/request/EventRequestStatusUpdateRequest.java
> +    private String status;
исправила

2023-06-28 13:55 UTC, catarena-s commented on ewm-service/src/main/java/ru/practicum/api/pub/PublicCompilationController.java
> +                                                @PositiveOrZero @RequestParam(value = "from", defaultValue = FROM) Integer from,
поправила

2023-06-28 16:15 UTC, z8q approved these changes

2023-06-28 16:15 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/service/user/UserServiceImpl.java
>      public void delete(long userId) {
А тут похоже зря убрала Transactional
Тут мы читаем и потом удаляем, обернуть в одну транзакцию было бы правильно

2023-06-29 11:00 UTC, merged