Feature subscriptions
catarena-s/java-explore-with-me pull request #5
Opened 2023-07-01 23:06 UTC by catarena-s

2023-07-02 23:40 UTC, z8q requested changes

2023-07-02 23:40 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/service/subs/FriendshipServiceImpl.java
> +    public List<FriendshipShortDto> getIncomingFriendRequests(long userId, String filter) {
можно было бы обернуть в `@Transactional(readOnly = true)`,
чтобы условие в 106-й строке точно выполнялось для 108

для метода getFriendshipRequests тоже применимо

2023-07-02 23:40 UTC, z8q commented on ewm-service/src/main/java/ru/practicum/service/subs/FriendshipServiceImpl.java
> +    public List<FriendshipShortDto> approveFriendship(long userId, List<Long> ids) {
В методе выполняется чтение findAllById и запись saveAll
стоит обернуть в транзакцию, чтобы проверки в строках 72-74 были действительными на момент сохранения.
Еще про FriendshipServiceImpl::approveFriendship сначала подумал, что рекурсивный вызов)

Для методов requestFriendship, rejectFriendship комментарий тоже применим

2023-07-03 11:17 UTC, catarena-s commented on ewm-service/src/main/java/ru/practicum/service/subs/FriendshipServiceImpl.java
> +    public List<FriendshipShortDto> approveFriendship(long userId, List<Long> ids) {
исправила

2023-07-03 11:17 UTC, catarena-s commented on ewm-service/src/main/java/ru/practicum/service/subs/FriendshipServiceImpl.java
> +    public List<FriendshipShortDto> getIncomingFriendRequests(long userId, String filter) {
исправила

2023-07-03 11:17 UTC, catarena-s commented on ewm-service/src/main/java/ru/practicum/service/subs/FriendshipServiceImpl.java
> +        final boolean noneMatchPending = subs.stream().noneMatch(s -> set.contains(s.getState()));
переименовала

2023-07-03 21:18 UTC, z8q approved these changes

2023-07-06 13:43 UTC, merged